#' Precipitation summary plot
#'
#' Function for plotting precipitation summary (line, matrix, box, and density)
#'
#' @import ggplot2
#' @importFrom gridExtra grid.arrange
#' @param dummie a csv generated by \code{\link{make_ts}}
#' @return ggplot object
#' @export

plot_summary <- function(dummie){
  p01 <- plot_line(dummie)
  p02 <- plot_heatmap(dummie)
  p03 <- plot_box(dummie)
  p04 <- plot_density(dummie)
  p05 <- grid.arrange(p01, p02, ncol = 1)
  p06 <- grid.arrange(p03, p04, ncol = 2)
  p00 <- grid.arrange(p05, p06, ncol = 1, heights = c(2, 1))
  return(p00)
}

