#' Precipitation line plot
#'
#' Function for plotting (line) time-series of area averaged precipitation.
#'
#' @import ggplot2
#' @param x a csv generated by \code{\link{fldmean}}
#' @param var a character string with the name of the variable to be used for the axis title
#' @param unit a character string with the variable's unit of measurement to be used for the axis title
#' @return gg object
#' @export

plot_line <- function(x, var = 'Precipitation', unit = 'mm'){
  if (length(unique(x$dataset)) <= 1){
    p00 <- ggplot(x, aes(x = date, y = value)) +
      geom_line(color = '#377eb8')
  } else {
    p00 <- ggplot(x, aes(x = date, y = value, color = dataset)) +
      geom_line()
  }
  p01 <- p00 +
    theme_bw() +
    labs(x = NULL, y = paste0('[', unit, ']'), title = var) +
    scale_x_date(date_breaks = "4 year", date_labels = "%Y-%m") +
    theme(plot.title = element_text(size=24),
          axis.text = element_text(size = 20),
          axis.title = element_text(size = 24))
  return(p01)
}