#' Precipitation line plot
#'
#' Function for plotting (line) time-series of area averaged precipitation.
#'
#' @import ggplot2
#' @param x a csv generated by \code{\link{make_ts}}
#' @param var a character string with the name of the variable to be used for the axis title
#' @param unit a character string with the variable's unit of measurement to be used for the axis title
#' @return ggplot object
#' @export

plot_line <- function(x, var = 'Precipitation', unit = 'mm'){
  if (is.null(x$name)){
    p00 <- ggplot(x, aes(x = date, y = value, color = '#377eb8'))
  } else {
    p00 <- ggplot(x, aes(x = date, y = value, color = name))
  }
  p01 <- p00 +
    geom_line() +
    theme_bw() +
    labs(x = NULL, y = paste0('[', unit, ']'), title = var) +
    scale_x_date(breaks = seq(as.Date("1840/1/1"), as.Date("2050/1/1"), 
                              by = "10 year"), date_labels = "%Y") +
    theme(plot.title = element_text(size=24),
          axis.text = element_text(size = 20),
          axis.title = element_text(size = 24))
  return(p01)
}